"""empty message

Revision ID: 3b69fa313e88
Revises: 67a374058943
Create Date: 2025-09-24 22:27:39.159501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b69fa313e88'
down_revision = '67a374058943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_fav_id_fkey', type_='foreignkey')
        batch_op.drop_column('fav_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planet_fav_id_fkey', 'favorite', ['fav_id'], ['id'])

    # ### end Alembic commands ###
