"""empty message

Revision ID: 67a374058943
Revises: c71d25890da8
Create Date: 2025-09-24 22:15:39.988320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a374058943'
down_revision = 'c71d25890da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_peoplefav_id_fkey', type_='foreignkey')
        batch_op.drop_column('peoplefav_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peoplefav_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('people_peoplefav_id_fkey', 'favorite', ['peoplefav_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###
